# Site settings
title: Damien's blog
header-img: img/city.gif
email: dameyawn@gmail.com
description: "And the art of under-engineering"
baseurl: ""
url: "http://damien.la"
twitter_username: dam13n
github_username:  dam13n
facebook_username:  damienster
linkedin_username: damiensutevski
disqus_shortname: dam13n

# Build settings
markdown: kramdown
highlighter: pygments
permalink: "/:year/:month/:day/:title"
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

exclude_pages: [ "Contact"]
